name: Deploy to AWS

on:
  push:
    paths:
      - app.js  # Sadece app.js dosyası değiştiğinde tetiklenir.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy app.js to AWS Server
        run: |
          # SSH ile bağlanarak eski app.js dosyasını sil ve yenisini kopyala
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_INSTANCE_IP }} "rm /path/to/your/app.js"
          scp -o StrictHostKeyChecking=no app.js ec2-user@${{ secrets.EC2_INSTANCE_IP }}:/path/to/your/app.js
